"""sync with MySQL structure

Revision ID: 5814eba382b8
Revises: 1ea31430ddae
Create Date: 2025-05-12 10:28:15.093051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5814eba382b8'
down_revision: Union[str, None] = '1ea31430ddae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('records', 'source',
               existing_type=mysql.ENUM('clinic', 'self_'),
               type_=sa.Enum('clinic', 'self', name='recordsource'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('records', 'source',
               existing_type=sa.Enum('clinic', 'self', name='recordsource'),
               type_=mysql.ENUM('clinic', 'self_'),
               existing_nullable=False)
    # ### end Alembic commands ###
