"""Remove unused status fields from doctor_patient

Revision ID: 692e6f2120e5
Revises: 004_fetal_monitoring
Create Date: 2025-07-03 10:55:16.795731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '692e6f2120e5'
down_revision: Union[str, None] = '004_fetal_monitoring'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('doctor_patient_ibfk_3', 'doctor_patient', type_='foreignkey')
    op.drop_column('doctor_patient', 'status_updated_by')
    op.drop_column('doctor_patient', 'status_updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor_patient', sa.Column('status_updated_at', mysql.DATETIME(), nullable=True))
    op.add_column('doctor_patient', sa.Column('status_updated_by', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('doctor_patient_ibfk_3', 'doctor_patient', 'users', ['status_updated_by'], ['id'])
    # ### end Alembic commands ###
