"""add_fetal_monitoring_tables

Revision ID: 72260757028e
Revises: 53b926878076
Create Date: 2025-07-03 03:03:20.006930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '72260757028e'
down_revision: Union[str, None] = '53b926878076'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Disabled all drop_index and drop_table commands that cause errors or are not needed
    # op.drop_index('ix_pregnancy_info_id', table_name='pregnancy_info')  # Disabled: table does not exist
    # op.drop_table('pregnancy_info')  # Disabled: table does not exist
    # op.drop_index('ix_fetal_monitoring_results_id', table_name='fetal_monitoring_results')  # Disabled: index does not exist
    # op.drop_index('session_id', table_name='fetal_monitoring_results')  # Disabled: index is needed in a foreign key constraint
    # op.drop_table('fetal_monitoring_results')  # Disabled: handled elsewhere or not needed
    # op.drop_index('ix_notifications_id', table_name='notifications')  # Disabled: index does not exist
    # op.drop_table('notifications')  # Disabled: handled elsewhere or not needed
    # op.drop_index('user_id', table_name='doctors')  # Disabled: index is needed in a foreign key constraint
    # op.drop_table('doctors')  # Disabled: handled elsewhere or not needed
    # op.drop_index('ix_fetal_heart_rate_readings_id', table_name='fetal_heart_rate_readings')  # Disabled: index does not exist
    # op.drop_table('fetal_heart_rate_readings')  # Disabled: handled elsewhere or not needed
    # op.drop_index('ix_fetal_monitoring_sessions_id', table_name='fetal_monitoring_sessions')  # Disabled: index does not exist
    # op.drop_table('fetal_monitoring_sessions')  # Disabled: handled elsewhere or not needed
    # op.drop_table('doctor_patient')  # Disabled: handled elsewhere or not needed
    # op.drop_table('records')  # Disabled: handled elsewhere or not needed
    # op.drop_index('email', table_name='users')  # Disabled: index does not exist
    # op.drop_index('ix_users_id', table_name='users')  # Disabled: index does not exist
    # op.drop_table('users')  # Disabled: handled elsewhere or not needed
    # op.drop_table('patients')  # Disabled: handled elsewhere or not needed
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('birth_date', sa.DATE(), nullable=True),
    sa.Column('address', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('medical_note', mysql.TEXT(), nullable=True),
    sa.Column('age', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('gender', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('phone', mysql.VARCHAR(length=20), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='patients_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('users',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('password_hash', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('role', mysql.ENUM('admin', 'doctor', 'patient'), nullable=False),
    sa.Column('photo_url', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_index('email', 'users', ['email'], unique=True)
    op.create_table('records',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('patient_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('doctor_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('source', mysql.ENUM('clinic', 'self'), nullable=False),
    sa.Column('bpm_data', mysql.JSON(), nullable=True),
    sa.Column('start_time', mysql.DATETIME(), nullable=False),
    sa.Column('end_time', mysql.DATETIME(), nullable=True),
    sa.Column('classification', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('notes', mysql.TEXT(), nullable=True),
    sa.Column('shared_with', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], name='fk_records_doctor_id_users'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name='fk_records_patient_id_patients_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shared_with'], ['users.id'], name='records_ibfk_3'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('doctor_patient',
    sa.Column('doctor_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('patient_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('assigned_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('note', mysql.TEXT(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], name='doctor_patient_ibfk_1', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name='doctor_patient_ibfk_2', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('doctor_id', 'patient_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('fetal_heart_rate_readings',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('timestamp', mysql.DATETIME(), nullable=False),
    sa.Column('bpm', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('signal_quality', mysql.FLOAT(), nullable=True),
    sa.Column('classification', mysql.ENUM('normal', 'bradycardia', 'tachycardia', 'irregular'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['fetal_monitoring_sessions.id'], name='fetal_heart_rate_readings_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_fetal_heart_rate_readings_id', 'fetal_heart_rate_readings', ['id'], unique=False)
    op.create_table('fetal_monitoring_sessions',
    sa.Column('id', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('patient_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('doctor_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('monitoring_type', mysql.ENUM('clinic', 'home'), nullable=False),
    sa.Column('gestational_age', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('start_time', mysql.DATETIME(), nullable=False),
    sa.Column('end_time', mysql.DATETIME(), nullable=True),
    sa.Column('notes', mysql.TEXT(), nullable=True),
    sa.Column('doctor_notes', mysql.TEXT(), nullable=True),
    sa.Column('shared_with_doctor', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], name='fetal_monitoring_sessions_ibfk_2'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name='fetal_monitoring_sessions_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_fetal_monitoring_sessions_id', 'fetal_monitoring_sessions', ['id'], unique=False)
    op.create_table('doctors',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('doctor_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_valid', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], name='doctors_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('user_id', 'doctors', ['doctor_id'], unique=True)
    op.create_table('notifications',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('from_patient_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('to_doctor_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('record_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', mysql.ENUM('unread', 'read'), nullable=False),
    sa.ForeignKeyConstraint(['from_patient_id'], ['patients.id'], name='notifications_ibfk_1'),
    sa.ForeignKeyConstraint(['record_id'], ['records.id'], name='notifications_ibfk_2'),
    sa.ForeignKeyConstraint(['to_doctor_id'], ['users.id'], name='notifications_ibfk_3'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_notifications_id', 'notifications', ['id'], unique=False)
    op.create_table('fetal_monitoring_results',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('overall_classification', mysql.ENUM('normal', 'concerning', 'abnormal'), nullable=False),
    sa.Column('average_bpm', mysql.FLOAT(), nullable=False),
    sa.Column('baseline_variability', mysql.FLOAT(), nullable=True),
    sa.Column('findings', mysql.JSON(), nullable=True),
    sa.Column('recommendations', mysql.JSON(), nullable=True),
    sa.Column('risk_level', mysql.ENUM('low', 'medium', 'high'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['fetal_monitoring_sessions.id'], name='fetal_monitoring_results_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('session_id', 'fetal_monitoring_results', ['session_id'], unique=True)
    op.create_index('ix_fetal_monitoring_results_id', 'fetal_monitoring_results', ['id'], unique=False)
    op.create_table('pregnancy_info',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('patient_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('gestational_age', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('last_menstrual_period', sa.DATE(), nullable=True),
    sa.Column('expected_due_date', sa.DATE(), nullable=True),
    sa.Column('is_high_risk', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('complications', mysql.JSON(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name='pregnancy_info_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_pregnancy_info_id', 'pregnancy_info', ['id'], unique=False)
    # ### end Alembic commands ###
